language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install --upgrade pip
    - pip install pyzmq PyYAML pycrypto msgpack-python jinja2 psutil futures tornado pytest-salt mock
    - git clone --depth=50 https://github.com/openSUSE/salt ../salt
    - git clone --depth=50 https://github.com/arbulu89/shaptools.git ../shaptools
    - pip install ../salt
    - pip install ../shaptools
    - pip install -U pytest pytest-cov coveralls
script:
    - ./tests/run.sh
    - coveralls
