language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install --upgrade pip
    - pip install --upgrade pytest
    - pip install pyzmq PyYAML pycrypto msgpack-python jinja2 psutil futures tornado pytest-salt mock pytest-cov enum34
    - git clone --depth=50 https://github.com/openSUSE/salt ../salt
    - rm ../salt/tests/conftest.py
    - git clone --depth=50 https://github.com/arbulu89/shaptools.git ../shaptools
    - pip install ../salt
    - pip install ../shaptools
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - ./tests/run.sh
after_script:
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT -p ../salt
